language: java
jdk:
    - openjdk7
    - openjdk6
    - oraclejdk7
before_install:
    - "sudo sed --in-place 's/security.provider.9/#security.provider.9/g' $JAVA_HOME/jre/lib/security/java.security"
    - env
install:
    - mvn install --define skipTests=true --errors --batch-mode
script:
    - mvn test --errors --batch-mode
after_success:
    - mvn test jacoco:report coveralls:jacoco --errors --batch-mode
