language: java
jdk:
    - openjdk7
    - openjdk6
    - oraclejdk7
env:
  global:
    - LOCKBOX_PUBLISH_VERSION=openjdk7
before_install:
    - "if [ 'openjdk7' == $TRAVIS_JDK_VERSION ]; sudo sed --in-place 's/security.provider.9/#security.provider.9/g' $JAVA_HOME/jre/lib/security/java.security; fi"
install:
    - mvn install --define skipTests=true --errors --batch-mode
script:
    - mvn test --errors --batch-mode
after_success:
    - "if [ $TRAVIS_JDK_VERSION == $LOCKBOX_PUBLISH_VERSION ]; then mvn test jacoco:report coveralls:jacoco --errors --batch-mode; fi"
