language: java
jdk:
    - oraclejdk7
    - openjdk7
    - openjdk6
before_install:
    - sudo apt-get update -qq
    - sudo apt-get upgrade -qq ca-certificates-java
install:
    - mvn install -DskipTests=true --errors --batch-mode
script:
    - mvn test jacoco:report coveralls:jacoco --errors --batch-mode
