language: java
install: mvn install -Dmaven.compiler.target=1.5 -Dmaven.compiler.source=1.5 -DskipTests=true -B
script: mvn test jacoco:report coveralls:jacoco -Dmaven.compiler.target=1.5 -Dmaven.compiler.source=1.5 -B
